'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { JsonFileRepository } = require('../lib/repositories/json-file-repository');
const { JsonAppRepository } = require('../lib/repositories/json-app-repository');
const { createMemoryStore } = require('../lib/memory-store');

test('native memory: author review, evidence, atomic chapter CAS, receipts, isolation and restart', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'molan-memory-native-'));
  let repository = new JsonFileRepository(dir), app = new JsonAppRepository(dir, { repository });
  t.after(async () => { await repository.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  await app.saveAccount({ userId: 'author', email: 'author@test.local' });
  await app.create({ id: 'n_memory', user: { userId: 'author', email: 'author@test.local' }, state: { title: 'T', volumes: [{ title: 'V', chapters: [{ id: 'c1', title: 'C', content: 'old' }] }] } });
  let store = createMemoryStore({ repository, getAccess: input => app.getAccess(input) });
  const scope = { userId: 'author', bookId: 'n_memory' };
  await assert.rejects(store.getMemory({ ...scope, userId: 'intruder' }), { code: 'BOOK_NOT_FOUND' });
  await app.saveAccount({ userId: 'reviewer', email: 'reviewer@test.local' });
  await repository.transaction(['n_memory'], tx => { const novel = tx.get('n_memory', 'novels', 'n_memory'); novel.members.reviewer = { role: 'reviewer', active: true }; tx.put('n_memory', 'novels', novel, novel.revision); });
  await assert.rejects(store.createChangeset({ ...scope, userId: 'reviewer', approval: true, operations: [] }), { code: 'FORBIDDEN' });
  const m = await store.saveManuscript({ ...scope, text: '阿青回到家中。', chapterId: 'c1', expectedRevision: 0, expectedNovelRevision: 0 });
  const extracted = await store.extract({ ...scope, manuscriptRevisionId: m.id });
  assert.equal(extracted.propositions.length, 1);
  assert.deepEqual(await store.extract({ ...scope, manuscriptRevisionId: m.id }), extracted);
  const review = await store.rewrite({ ...scope, contract: { lockedPropositions: ['阿青'] }, manuscriptRevisionId: m.id });
  assert.equal(review.review.passed, true);
  const cs = await store.createChangeset({ ...scope, manuscriptRevisionId: m.id, rewriteReviewId: review.review.id,
    operations: [{ type: 'INSERT_FACT', payload: { id: 'fact1', propositionId: extracted.propositions[0].id, supportingEvidenceIds: [extracted.evidence[0].id] } }] });
  await assert.rejects(store.commitChangeset({ ...scope, changesetId: cs.id }), { code: 'changeset_not_approved' });
  await store.approveChangeset({ ...scope, changesetId: cs.id });
  const receipt = await store.commitChangeset({ ...scope, changesetId: cs.id, expectedStateVersion: 1, idempotencyKey: 'save-one' });
  assert.equal(receipt.novelRevision, 1);
  assert.equal((await app.read({ userId: 'author', projectId: 'n_memory' })).state.volumes[0].chapters[0].content, '<p>阿青回到家中。</p>');
  assert.equal((await store.commitChangeset({ ...scope, changesetId: cs.id, expectedStateVersion: 1, idempotencyKey: 'save-one' })).replayed, true);
  assert.equal((await store.commitChangeset({ ...scope, changesetId: cs.id, expectedStateVersion: 1, idempotencyKey: 'save-alias' })).replayed, true);
  await assert.rejects(store.commitChangeset({ ...scope, changesetId: cs.id, expectedStateVersion: 2, idempotencyKey: 'new-alias' }), { code: 'IDEMPOTENCY_CONFLICT' });
  await assert.rejects(store.commitChangeset({ ...scope, changesetId: cs.id, expectedStateVersion: 2, idempotencyKey: 'save-one' }), { code: 'IDEMPOTENCY_CONFLICT' });
  assert.equal((await store.processProjections(scope)).synced, true);
  const op = (await store.listOperations(scope))[0];
  await store.revertOperation({ ...scope, operationId: op.id, reason: '作者修正' });
  assert.equal((await store.getMemory(scope)).length, 0);
  await repository.close();
  repository = new JsonFileRepository(dir); app = new JsonAppRepository(dir, { repository });
  store = createMemoryStore({ repository, getAccess: input => app.getAccess(input) });
  assert.equal((await store.getChangeset({ ...scope, changesetId: cs.id })).committedAt > 0, true);
  assert.equal((await store.commitChangeset({ ...scope, changesetId: cs.id, expectedStateVersion: 1, idempotencyKey: 'save-alias' })).replayed, true);
  assert.equal((await store.listOperations(scope)).filter(op => op.changesetId === cs.id).length, 1);
});

test('native memory refuses invalid operations, stale body, hidden disclosure and budget overflow', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'molan-memory-guard-'));
  const repository = new JsonFileRepository(dir), app = new JsonAppRepository(dir, { repository });
  t.after(async () => { await repository.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  await app.saveAccount({ userId: 'u', email: 'u@test.local' });
  await app.create({ id: 'n_guard', user: { userId: 'u', email: 'u@test.local' }, state: { volumes: [{ chapters: [{ id: 'c', content: 'original' }] }] } });
  const store = createMemoryStore({ repository, getAccess: input => app.getAccess(input) }), s = { userId: 'u', bookId: 'n_guard' };
  const bad = await store.createChangeset({ ...s, operations: [{ type: 'INSERT_FACT', payload: { id: 'bad', propositionId: 'missing' } }] });
  await store.approveChangeset({ ...s, changesetId: bad.id });
  await assert.rejects(store.commitChangeset({ ...s, changesetId: bad.id }), { code: 'MEMORY_REFERENCE_INVALID' });
  assert.equal((await store.listOperations(s)).length, 0);
  const m = await store.saveManuscript({ ...s, text: '秘密是青石。', chapterId: 'c', expectedRevision: 0, expectedNovelRevision: 0 });
  const extracted = await store.extract({ ...s, manuscriptRevisionId: m.id });
  const rv = await store.rewrite({ ...s, manuscriptRevisionId: m.id, contract: {} });
  const stale = await store.createChangeset({ ...s, manuscriptRevisionId: m.id, rewriteReviewId: rv.review.id });
  await app.saveCAS({ userId: 'u', projectId: 'n_guard', expectedRevision: 0, state: { volumes: [{ chapters: [{ id: 'c', content: 'changed' }] }] } });
  await assert.rejects(store.approveChangeset({ ...s, changesetId: stale.id }), { code: 'CONTENT_VERSION_CONFLICT' });
  const cs = await store.createChangeset({ ...s, operations: [{ type: 'INSERT_FACT', payload: { id: 'f', propositionId: extracted.propositions[0].id } }] });
  await store.approveChangeset({ ...s, changesetId: cs.id }); await store.commitChangeset({ ...s, changesetId: cs.id });
  const hide = await store.createChangeset({ ...s, operations: [{ type: 'SET_DISCLOSURE', payload: { id: 'hide', targetInfoId: 'f', policyType: 'hide' } }] });
  await store.approveChangeset({ ...s, changesetId: hide.id }); await store.commitChangeset({ ...s, changesetId: hide.id });
  const manifest = await store.assembleContext({ ...s, budgetTokens: 1000 });
  assert.equal(manifest.writingPackage.facts.length, 0); assert.equal(manifest.auditPackage.facts.length, 1);
  await assert.rejects(store.assembleContext({ ...s, mandatoryItems: ['x'.repeat(200)], budgetTokens: 20 }), { code: 'CONTEXT_BUDGET_EXCEEDED' });
});
