'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { JsonAppRepository } = require('../lib/repositories/json-app-repository');
const { createNativeProjectService } = require('../services/native-project-service');
test('native projects preserve scoped resources, CAS, history and workspace membership', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'native-project-http-'));
  const repository = new JsonAppRepository(dir); t.after(async () => { await repository.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  await repository.saveAccount({ userId: 'owner', email: 'owner@t' }); await repository.saveAccount({ userId: 'other', email: 'other@t' });
  await repository.create({ id: 'n_project', user: { userId: 'owner', email: 'owner@t' }, state: { title: 'Test', volumes: [] } });
  let actor = 'owner';
  const service = createNativeProjectService({ repository, getAuthUser: () => ({ user: { userId: actor } }), readBody: async req => req.body || {}, json: (res, status, body) => { res.status = status; res.body = body; } });
  const call = async (method, url, body, headers = {}) => { const res = { setHeader(name, value) { this[name] = value; } }; assert.equal(await service.dispatch({ method, url, body, headers }, res, new URL(url, 'http://x').pathname), true); return res; };
  let result = await call('GET', '/api/workspaces'); assert.equal(result.status, 200); const workspaceId = result.body.workspaces[0].id;
  result = await call('POST', '/api/workspaces', { name: 'New' }); assert.equal(result.status, 201); assert.equal(typeof result.body.workspaceId, 'string');
  result = await call('POST', '/api/novels/n_project/resources/character', { id: 'hero', payload: { name: 'Hero' } }); assert.equal(result.status, 201); assert.equal(result.body.resource.revision, 1);
  result = await call('GET', '/api/novels/n_project/resources/character/hero'); assert.equal(result.ETag, '"resource-hero-1"');
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'New hero' } }); assert.equal(result.status, 428);
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'Bad' } }, { 'if-match': 'garbage-1' }); assert.equal(result.status, 400);
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'Bad' } }, { 'if-match': '"resource-other-1"' }); assert.equal(result.status, 400);
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'New hero' } }, { 'if-match': '"resource-hero-1"' }); assert.equal(result.status, 200);
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'Stale' }, revision: 1 }); assert.equal(result.status, 412);
  result = await call('GET', '/api/novels/n_project/resources/character/hero/history'); assert.equal(result.body.versions.length, 2);
  result = await call('POST', '/api/novels/n_project/resources/character/hero/history/1/restore', { revision: 2 }); assert.equal(result.body.resource.payload.name, 'Hero'); assert.equal(result.body.resource.revision, 3);
  result = await call('GET', `/api/workspaces/${workspaceId}/projects/n_project/members`); assert.equal(result.body.members[0].userId, 'owner');
  result = await call('POST', `/api/workspaces/${workspaceId}/members`, { userId: 'other', role: 'member' }); assert.equal(result.status, 200);
  result = await call('GET', `/api/workspaces/${workspaceId}/members`); assert.equal(result.body.members.some(m => m.userId === 'other'), true);
  result = await call('POST', `/api/workspaces/${workspaceId}/projects/n_project/members`, { userId: 'other', role: 'editor', canSpend: true, canExport: true }); assert.equal(result.status, 200);
  result = await call('POST', `/api/workspaces/${workspaceId}/projects/n_project/members`, { userId: 'other', transferOwner: true, aclRevision: result.body.aclRevision }); assert.equal(result.status, 200);
  result = await call('DELETE', `/api/workspaces/${workspaceId}/members`, { userId: 'other' }); assert.equal(result.status, 200);
  actor = 'other'; result = await call('GET', '/api/novels/n_project/resources/character/hero'); assert.equal(result.status, 404);
  result = await call('GET', `/api/workspaces/${workspaceId}/projects`); assert.equal(result.status, 404);
});
