'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { JsonAppRepository } = require('../lib/repositories/json-app-repository');
const { createNativeProjectService } = require('../services/native-project-service');
test('native projects preserve scoped resources, CAS, history and workspace membership', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'native-project-http-'));
  const repository = new JsonAppRepository(dir); t.after(async () => { await repository.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  await repository.saveAccount({ userId: 'owner', email: 'owner@t' }); await repository.saveAccount({ userId: 'other', email: 'other@t' });
  await repository.create({ id: 'n_project', user: { userId: 'owner', email: 'owner@t' }, state: { title: 'Test', volumes: [] } });
  let actor = 'owner';
  const service = createNativeProjectService({ repository, getAuthUser: () => ({ user: { userId: actor } }), readBody: async req => req.body || {}, json: (res, status, body) => { res.status = status; res.body = body; } });
  const call = async (method, url, body, headers = {}) => { const res = { setHeader(name, value) { this[name] = value; } }; assert.equal(await service.dispatch({ method, url, body, headers }, res, new URL(url, 'http://x').pathname), true); return res; };
  let result = await call('GET', '/api/workspaces'); assert.equal(result.status, 200); const workspaceId = result.body.workspaces[0].id;
  result = await call('POST', '/api/workspaces', { name: 'New' }); assert.equal(result.status, 201); assert.equal(typeof result.body.workspaceId, 'string');
  result = await call('POST', '/api/novels/n_project/resources/character', { id: 'hero', payload: { name: 'Hero' } }); assert.equal(result.status, 201); assert.equal(result.body.resource.revision, 1);
  result = await call('GET', '/api/novels/n_project/resources/character/hero'); assert.equal(result.ETag, '"resource-hero-1"');
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'New hero' } }); assert.equal(result.status, 428);
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'Bad' } }, { 'if-match': 'garbage-1' }); assert.equal(result.status, 400);
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'Bad' } }, { 'if-match': '"resource-other-1"' }); assert.equal(result.status, 400);
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'New hero' } }, { 'if-match': '"resource-hero-1"' }); assert.equal(result.status, 200);
  result = await call('PATCH', '/api/novels/n_project/resources/character/hero', { payload: { name: 'Stale' }, revision: 1 }); assert.equal(result.status, 412);
  result = await call('GET', '/api/novels/n_project/resources/character/hero/history'); assert.equal(result.body.versions.length, 2);
  result = await call('POST', '/api/novels/n_project/resources/character/hero/history/1/restore', { revision: 2 }); assert.equal(result.body.resource.payload.name, 'Hero'); assert.equal(result.body.resource.revision, 3);
  result = await call('GET', `/api/workspaces/${workspaceId}/projects/n_project/members`); assert.equal(result.body.members[0].userId, 'owner');
  result = await call('POST', `/api/workspaces/${workspaceId}/members`, { userId: 'other', role: 'member' }); assert.equal(result.status, 200);
  result = await call('GET', `/api/workspaces/${workspaceId}/members`); assert.equal(result.body.members.some(m => m.userId === 'other'), true);
  result = await call('POST', `/api/workspaces/${workspaceId}/projects/n_project/members`, { userId: 'other', role: 'editor', canSpend: true, canExport: true }); assert.equal(result.status, 200);
  result = await call('POST', `/api/workspaces/${workspaceId}/projects/n_project/members`, { userId: 'other', transferOwner: true, aclRevision: result.body.aclRevision }); assert.equal(result.status, 200);
  result = await call('DELETE', `/api/workspaces/${workspaceId}/members`, { userId: 'other' }); assert.equal(result.status, 200);
  actor = 'other'; result = await call('GET', '/api/novels/n_project/resources/character/hero'); assert.equal(result.status, 404);
  result = await call('GET', `/api/workspaces/${workspaceId}/projects`); assert.equal(result.status, 404);
});
test('native package HTTP verifies hashes, CAS and atomic reference snapshots', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'native-package-http-'));
  const repository = new JsonAppRepository(dir); t.after(async () => { await repository.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  await repository.saveAccount({ userId: 'owner', email: 'package@t' });
  await repository.create({ id: 'n_package', user: { userId: 'owner', email: 'package@t' }, state: { title: 'Original', volumes: [{ chapters: [{ id: 'chapter', content: 'body' }] }] } });
  const service = createNativeProjectService({ repository, getAuthUser: () => ({ user: { userId: 'owner' } }), readBody: async req => req.body || {}, json: (res, status, body) => { res.status = status; res.body = body; } });
  const call = async (method, url, body) => { const res = {}; assert.equal(await service.dispatch({ method, url, body, headers: {} }, res, url), true); return res; };
  const projectPackage = require('../lib/project-package');
  const snapshot = await repository.readProjectPackageSnapshot({ userId: 'owner', projectId: 'n_package' });
  const pack = resources => projectPackage.exportProjectPackage({ projectId: 'n_package', workspaceId: snapshot.novel.workspaceId, ownerUserId: 'owner', state: snapshot.novel.state, assets: { projectResources: resources } });
  let result = await call('GET', '/api/novels/n_package/package'); assert.equal(result.status, 200); const exported = result.body.package;
  result = await call('POST', '/api/novels/n_package/package/restore', { package: exported, revision: 0 }); assert.equal(result.status, 200); assert.equal(result.body.revision, 1);
  result = await call('POST', '/api/novels/n_package/package/restore', { package: exported, revision: 0 }); assert.equal(result.status, 412);
  const tampered = structuredClone(exported); tampered.files['data/state.json'].content += 'tamper';
  result = await call('POST', '/api/novels/n_package/package/import', { package: tampered }); assert.equal(result.status, 409);
  result = await call('POST', '/api/novels/n_package/package/restore', { package: tampered, revision: 1 }); assert.equal(result.status, 422);
  const before = await repository.read({ userId: 'owner', projectId: 'n_package' });
  const dangling = pack([{ id: 'new_character', kind: 'character', payload: { name: 'New', references: [{ id: 'missing_character', kind: 'character' }] } }]);
  result = await call('POST', '/api/novels/n_package/package/restore', { package: dangling, revision: 1 }); assert.equal(result.status, 422);
  assert.equal((await repository.read({ userId: 'owner', projectId: 'n_package' })).revision, before.revision);
  assert.equal((await repository.listResources({ userId: 'owner', projectId: 'n_package' })).length, 0);
  assert.equal((await repository.listResourceVersions({ userId: 'owner', projectId: 'n_package', id: 'new_character' })).length, 0);
  const mutual = pack([{ id: 'a', kind: 'character', payload: { name: 'A', references: [{ id: 'b', kind: 'character' }] } }, { id: 'b', kind: 'character', payload: { name: 'B', references: [{ id: 'a', kind: 'character' }] } }]);
  result = await call('POST', '/api/novels/n_package/package/restore', { package: mutual, revision: 1 }); assert.equal(result.status, 200);
  assert.equal((await repository.listResources({ userId: 'owner', projectId: 'n_package' })).length, 2);
  assert.equal((await repository.read({ userId: 'owner', projectId: 'n_package' })).state.knowledge.entities.a.name, 'A');
});
